matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && CXX_FOR_BUILD=g++-8 && CC_FOR_BUILD=gcc-8 && TRAVIS_COMPILER=g++-8"

language: cpp

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  # install GCC ARM from GNU ARM Embedded Toolchain PPA
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-arm-embedded

  # build GNU Make 4.1 from source
  - wget http://ftp.gnu.org/gnu/make/make-4.1.tar.gz
  - tar xvf make-4.1.tar.gz
  - cd make-4.1
  - ./configure
  - make -j16
  - sudo make install
  - cd ..
  - rm -rf make-4.1

  # add Make to path
  - export PATH=/usr/local/bin/:$PATH

  # make gcc 8.2 default
  - sudo ln -s /usr/bin/gcc-8.2 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8.2 /usr/local/bin/g++

  # compile googletest/mock libraries
  - sudo apt-get -y install cmake
  - cd $TRAVIS_BUILD_DIR/Robot/ && mkdir googletest_clone && cd googletest_clone
  - git clone https://github.com/google/googletest.git
  - cd googletest && mkdir build && cd build
  - cmake .. 
  - make -j16 DGTEST_CREATE_SHARED_LIBRARY=1

script:
  - g++ -v
  - cd $TRAVIS_BUILD_DIR/Robot/
  - make -j16 TARGET=F4 all
  - make -j16 TARGET=F7 all
