ROBOCUP_ROBOT_ID: 2
ROBOCUP_TEAM_COLOR: red
ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10001
ROBOCUP_MIRROR_SERVER_IP: 127.0.0.1
ROBOCUP_GAMECONTROLLER_IP: 127.0.1.1
X_POS: 1
Y_POS: -3.06
ANGLE: 1.57
ROBOT_NAME: robot2
COMPETITION: true
GOALIE: false
ENABLE_PYBULLET: false
TEAM_ID: 16
