# Only used if local_mode is false
target_host: 127.0.0.1
target_port: 3737
receive_port: 3737

# Only used when target_host is 127.0.0.1 (local mode)
# the team communication will bind to one of these ports and send to the other ports, depending on its bot_id
local_target_ports:
  - 4001
  - 4002
  - 4003
  - 4004

# Rate of published messages in Hz
rate: 65

# average walking speed in [m/s]
avg_walking_speed: 0.2

# lifetime of data [s]
lifetime: 1

# ROS Topics
team_data_topic: 'team_data'
strategy_topic: 'strategy'
time_to_ball_topic: 'time_to_ball'
pose_topic: 'pose_with_covariance'
ball_topic: 'ball_position_relative_filtered'
ball_velocity_topic: 'ball_relative_movement'
obstacle_topic: 'obstacles_relative'
cmd_vel_topic: 'cmd_vel'
gamestate_topic: 'gamestate'
move_base_goal_topic: 'move_base/current_goal'