soccerbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  torso_right_hip_side_position_controller:
    type: position_controllers/JointPositionController
    joint: torso_right_hip_side
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_hip_side_hip_front_position_controller:
    type: position_controllers/JointPositionController
    joint: right_hip_side_hip_front
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_hip_front_thigh_position_controller:
    type: position_controllers/JointPositionController
    joint: right_hip_front_thigh
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_thigh_calve_position_controller:
    type: position_controllers/JointPositionController
    joint: right_thigh_calve
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_calve_ankle_position_controller:
    type: position_controllers/JointPositionController
    joint: right_calve_ankle
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_ankle_foot_position_controller:
    type: position_controllers/JointPositionController
    joint: right_ankle_foot
    pid: {p: 100.0, i: 0.01, d: 10.0}
  torso_left_hip_side_position_controller:
    type: position_controllers/JointPositionController
    joint: torso_left_hip_side
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_hip_side_hip_front_position_controller:
    type: position_controllers/JointPositionController
    joint: left_hip_side_hip_front
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_hip_front_thigh_position_controller:
    type: position_controllers/JointPositionController
    joint: left_hip_front_thigh
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_thigh_calve_position_controller:
    type: position_controllers/JointPositionController
    joint: left_thigh_calve
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_calve_ankle_position_controller:
    type: position_controllers/JointPositionController
    joint: left_calve_ankle
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_ankle_foot_position_controller:
    type: position_controllers/JointPositionController
    joint: left_ankle_foot
    pid: {p: 100.0, i: 0.01, d: 10.0}
  torso_right_bicep_position_controller:
    type: position_controllers/JointPositionController
    joint: torso_right_bicep
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_bicep_forearm_position_controller:
    type: position_controllers/JointPositionController
    joint: right_bicep_forearm
    pid: {p: 100.0, i: 0.01, d: 10.0}
  torso_left_bicep_position_controller:
    type: position_controllers/JointPositionController
    joint: torso_left_bicep
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_bicep_forearm_position_controller:
    type: position_controllers/JointPositionController
    joint: left_bicep_forearm
    pid: {p: 100.0, i: 0.01, d: 10.0}
  torso_neck_position_controller:
    type: position_controllers/JointPositionController
    joint: torso_neck
    pid: {p: 100.0, i: 0.01, d: 10.0}
  neck_head_position_controller:
    type: position_controllers/JointPositionController
    joint: neck_head
    pid: {p: 100.0, i: 0.01, d: 10.0}

