# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
torso_right_hip_side:
  type: effort_controllers/JointPositionController
  joint: torso_right_hip_side
  pid: {p: 10.0, i: 0.0, d: 0.001}
right_hip_side_hip_front:
  type: effort_controllers/JointPositionController
  joint: right_hip_side_hip_front
  pid: {p: 10.0, i: 0.0, d: 0.001}
right_hip_front_thigh:
  type: effort_controllers/JointPositionController
  joint: right_hip_front_thigh
  pid: {p: 10.0, i: 0.0, d: 0.001}
right_thigh_calve:
  type: effort_controllers/JointPositionController
  joint: right_thigh_calve
  pid: {p: 10.0, i: 0.0, d: 0.001}
right_calve_ankle:
  type: effort_controllers/JointPositionController
  joint: right_calve_ankle
  pid: {p: 10.0, i: 0.0, d: 0.001}
right_ankle_foot:
  type: effort_controllers/JointPositionController
  joint: right_ankle_foot
  pid: {p: 10.0, i: 0.0, d: 0.001}

torso_left_hip_side:
  type: effort_controllers/JointPositionController
  joint: torso_left_hip_side
  pid: {p: 10.0, i: 0.0, d: 0.001}
left_hip_side_hip_front:
  type: effort_controllers/JointPositionController
  joint: left_hip_side_hip_front
  pid: {p: 30.0, i: 0.0, d: 0.001}
left_hip_front_thigh:
  type: effort_controllers/JointPositionController
  joint: left_hip_front_thigh
  pid: {p: 10.0, i: 0.0, d: 0.001}
left_thigh_calve:
  type: effort_controllers/JointPositionController
  joint: left_thigh_calve
  pid: {p: 10.0, i: 0.0, d: 0.001}
left_calve_ankle:
  type: effort_controllers/JointPositionController
  joint: left_calve_ankle
  pid: {p: 10.0, i: 0.0, d: 0.001}
left_ankle_foot:
  type: effort_controllers/JointPositionController
  joint: left_ankle_foot
  pid: {p: 10.0, i: 0.0, d: 0.001}

torso_right_bicep:
  type: effort_controllers/JointPositionController
  joint: torso_right_bicep
  pid: {p: 10.0, i: 0.0, d: 0.001}
right_bicep_forearm:
  type: effort_controllers/JointPositionController
  joint: right_bicep_forearm
  pid: {p: 10.0, i: 0.0, d: 0.001}
torso_left_bicep:
  type: effort_controllers/JointPositionController
  joint: torso_left_bicep
  pid: {p: 10.0, i: 0.0, d: 0.001}
left_bicep_forearm:
  type: effort_controllers/JointPositionController
  joint: left_bicep_forearm
  pid: {p: 10.0, i: 0.0, d: 0.001}

torso_neck:
  type: effort_controllers/JointPositionController
  joint: torso_neck
  pid: {p: 10.0, i: 0.0, d: 0.001}
neck_head:
  type: effort_controllers/JointPositionController
  joint: neck_head
  pid: {p: 10.0, i: 0.0, d: 0.001}
