# Path parameters
torso_height: 0.36 # 24 to 38 not sure
walking_hip_height: 0.185 # not sure

bodystep_size_default: 0.001
bodystep_size_short_backwards: 0.001
bodystep_size_short_forwards: 0.001

steps_per_second_default: 2.5
foot_separation: 0.0415
step_height: 0.03
torso_offset_x: 0.017 # positive is forward
torso_offset_x_ready: 0.012
torso_offset_pitch_ready: -0.1
crotch_sidediff_sway: -0.01
#get_ready_rate: 0.03
#pre_footstep_ratio: 0.05
post_footstep_ratio: 0.2

walking_Kp: 0.8
walking_Ki: 0.0005
walking_Kd: 0.0
walking_setpoint: -0.05

standing_Kp: 0.15
standing_Ki: 0.001
standing_Kd: 0.0
